<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMHyx5HO\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMHyx5HO/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerMHyx5HO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerMHyx5HO\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerMHyx5HO\srcApp_KernelProdContainer([
    'container.build_hash' => 'MHyx5HO',
    'container.build_id' => '904d59f8',
    'container.build_time' => 1600707195,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMHyx5HO');
