<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'actualites' => [[], ['_controller' => 'App\\Controller\\ActualitesController::index'], [], [['text', '/actualites']], [], []],
    'association' => [[], ['_controller' => 'App\\Controller\\AssociationController::index'], [], [['text', '/association']], [], []],
    'blog' => [[], ['_controller' => 'App\\Controller\\BlogController::index'], [], [['text', '/']], [], []],
    'show' => [['id'], ['_controller' => 'App\\Controller\\BlogController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/blog']], [], []],
    'citoyens' => [[], ['_controller' => 'App\\Controller\\CitoyensController::index'], [], [['text', '/citoyens']], [], []],
    'compte_rendus' => [[], ['_controller' => 'App\\Controller\\CompteRendusController::index'], [], [['text', '/compte/rendus']], [], []],
    'show_compterendu' => [['id'], ['_controller' => 'App\\Controller\\CompteRendusController::showCompteRendu'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/detail']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], []],
    'inscription' => [[], ['_controller' => 'App\\Controller\\CotisationController::paypal'], [], [['text', '/inscription']], [], []],
    'formulaire' => [[], ['_controller' => 'App\\Controller\\FormulaireController::index'], [], [['text', '/formulaire']], [], []],
    'showform' => [['id'], ['_controller' => 'App\\Controller\\FormulaireController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/formulaire']], [], []],
    'gallery' => [[], ['_controller' => 'App\\Controller\\GalleryController::index'], [], [['text', '/gallery']], [], []],
    'petition' => [[], ['_controller' => 'App\\Controller\\PetitionController::index'], [], [['text', '/petition']], [], []],
    'singlepetition' => [['id'], ['_controller' => 'App\\Controller\\PetitionController::singlepetition'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/petition']], [], []],
    'security_login_index' => [[], ['_controller' => 'App\\Controller\\SecurityController::index'], [], [['text', '/login']], [], []],
    'security_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/connexion']], [], []],
    'security_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'security_registration' => [[], ['_controller' => 'App\\Controller\\SecurityController::registration'], [], [['text', '/register']], [], []],
    'user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user']], [], []],
    'easyadmin' => [[], ['_controller' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Controller\\EasyAdminController::indexAction'], [], [['text', '/admin/']], [], []],
];
