easy_admin:
  entities:
    Cotisation:
      class: App\Entity\Cotisation
      list:
        title: "Liste des adhésions"
        fields:
          - { property: 'id' }
          - { property: 'nom' }
          - { property: 'prenom'}
          - { property: 'mail'}
          - { property: 'Telephone'}
          - { property: 'Montant'}
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
          - {name: 'new', icon: 'plus', label: 'Ajouter un adhérant', css_class: 'btn btn-success'}
