easy_admin:
  entities:
    Petition:
      class: App\Entity\Petition
      edit:
        title: "Modifier une pétition"
        fields:
          - {property: 'title'}
          - {property: 'description', type: 'fos_ckeditor'}
          - {property: 'imageFile', type: 'vich_image' }
        actions:
          - {name: 'list', icon: 'tag', label: 'Liste des pétitions', css_class: 'btn btn-success'}
          - {name: 'delete', icon: 'trash', label: "Supprimer la pétition", css_class: 'btn btn-danger'}
      new:
        title: "Ajouter une pétition"
        actions:
          - {name: 'list', icon: 'tag', label: 'Liste des pétitions', css_class: 'btn btn-success'}
          - {name: 'delete', icon: 'trash', label: "Supprimer la pétition", css_class: 'btn btn-danger'}
        fields:
          - {property: 'title'}
          - {property: 'description', type: 'fos_ckeditor'}
          - {property: 'imageFile', type: 'vich_image' }
          - {property: 'date'}
      list:
        title: "Liste des pétitions"
        fields:
          - { property: 'id' }
          - { property: 'title' }
          - { property: 'description'}
          - { property: 'img', type: 'image', base_path: '%app.path.product_images%' }
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
          - {name: 'new', icon: 'plus', label: 'Ajouter une pétition', css_class: 'btn btn-success'}
