easy_admin:
  entities:
    TextGallery:
      class: App\Entity\TextGallery
      edit:
        title: "Modifier un texte"
        fields:
          - {property: 'text', type: 'fos_ckeditor'}
        actions:
          - {name: 'list', icon: 'tag', label: 'Liste des textes', css_class: 'btn btn-success'}
          - {name: 'delete', icon: 'trash', label: "Supprimer le texte", css_class: 'btn btn-danger'}
      new:
        title: "Ajouter un texte"
        actions:
          - {name: 'list', icon: 'tag', label: 'Liste des textes', css_class: 'btn btn-success'}
          - {name: 'delete', icon: 'trash', label: "Supprimer le texte", css_class: 'btn btn-danger'}
        fields:
          - {property: 'text', type: 'fos_ckeditor'}
      list:
        title: "Liste des textes"
        fields:
          - { property: 'text'}
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
          - {name: 'new', icon: 'plus', label: 'Ajouter un texte', css_class: 'btn btn-success'}
