<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2w.ti9T' shared service.

return $this->privates['.service_locator.2w.ti9T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BlogController::index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\CotisationController::paypal' => ['privates', '.service_locator.3kgdW_8', 'get_ServiceLocator_3kgdW8Service.php', true],
    'App\\Controller\\FormulaireController::index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\FormulaireController::show' => ['privates', '.service_locator.3kgdW_8', 'get_ServiceLocator_3kgdW8Service.php', true],
    'App\\Controller\\GalleryController::index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\PetitionController::index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\PetitionController::singlepetition' => ['privates', '.service_locator.rWF2xTt', 'get_ServiceLocator_RWF2xTtService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\BlogController:index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\CotisationController:paypal' => ['privates', '.service_locator.3kgdW_8', 'get_ServiceLocator_3kgdW8Service.php', true],
    'App\\Controller\\FormulaireController:index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\FormulaireController:show' => ['privates', '.service_locator.3kgdW_8', 'get_ServiceLocator_3kgdW8Service.php', true],
    'App\\Controller\\GalleryController:index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\PetitionController:index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\PetitionController:singlepetition' => ['privates', '.service_locator.rWF2xTt', 'get_ServiceLocator_RWF2xTtService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
], [
    'App\\Controller\\BlogController::index' => '?',
    'App\\Controller\\CotisationController::paypal' => '?',
    'App\\Controller\\FormulaireController::index' => '?',
    'App\\Controller\\FormulaireController::show' => '?',
    'App\\Controller\\GalleryController::index' => '?',
    'App\\Controller\\PetitionController::index' => '?',
    'App\\Controller\\PetitionController::singlepetition' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\BlogController:index' => '?',
    'App\\Controller\\CotisationController:paypal' => '?',
    'App\\Controller\\FormulaireController:index' => '?',
    'App\\Controller\\FormulaireController:show' => '?',
    'App\\Controller\\GalleryController:index' => '?',
    'App\\Controller\\PetitionController:index' => '?',
    'App\\Controller\\PetitionController:singlepetition' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
]);
