<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.rWF2xTt' shared service.

return $this->privates['.service_locator.rWF2xTt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
], [
    'managerRegistry' => '?',
]);
