<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZVVmkmJ\srcApp_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZVVmkmJ/srcApp_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerZVVmkmJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevContainer::class, false)) {
    \class_alias(\ContainerZVVmkmJ\srcApp_KernelDevContainer::class, srcApp_KernelDevContainer::class, false);
}

return new \ContainerZVVmkmJ\srcApp_KernelDevContainer([
    'container.build_hash' => 'ZVVmkmJ',
    'container.build_id' => 'f8084674',
    'container.build_time' => 1590434705,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZVVmkmJ');
