<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM7pOA7W\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM7pOA7W/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM7pOA7W.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM7pOA7W\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM7pOA7W\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'M7pOA7W',
    'container.build_id' => 'de1428c1',
    'container.build_time' => 1590434812,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM7pOA7W');
